spring:
  application:
    name: url-shortener

  data:
    mongodb:
      uri: mongodb://localhost:27017/urlshortener

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: url-shortener

app:
  redis:
    host: localhost
    port: 6379
  url:
    expiration-days: 7
    base-domain: http://localhost:8080
  hash:
    length: 8
    strategy: base62
